# 用来定义 docker compose
# 用来编排 docker 相关服务
version: '1'

services:
  ccc-monitor-clickhouse:
    image: clickhouse:25.10
    container_name: ccc-monitor-clickhouse
    # 暴露端口
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USERNAME}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=monitor
    # 数据同步至主机
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
  ccc-monitor-postgres:
    image: postgres:18.1
    container_name: ccc-monitor-postgres
    # 暴露端口
    ports:
      - '5432:5432' # 左边这个是服务主机的端口，右边docker容器内服务启动端口
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=monitor
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgresql_data:/var/lib/postgresql
